fix: use SampleLevel instead of Sample in ray tracing shader
Ray tracing shaders (closest hit, any hit, intersection) cannot use
implicit LOD sampling (.Sample()) - they require explicit LOD via
.SampleLevel().

Changed SampleTexture() in closesthit.rchit to use SampleLevel with
LOD 0.0 (no mipmapping in current implementation).

This fixes shader compilation error:
'sampling with implicit lod is only allowed in fragment and compute shaders'